name: Trigger auto deployment for aba-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/aba-app-AutoDeployTrigger-6f67d8b2-f84a-4ba1-b24e-088ed9b66a0f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ABAAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ABAAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ABAAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: testoidcreg1.azurecr.io
          registryUsername: ${{ secrets.ABAAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ABAAPP_REGISTRY_PASSWORD }}
          containerAppName: aba-app
          resourceGroup: ana-rg
          imageToBuild: testoidcreg1.azurecr.io/aba-app:${{ github.sha }}
          dockerfilePath: Dockerfile


