name: Trigger auto deployment for contexistdeploy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ TestingSP ]
    paths:
    - 'result/**'
    - '.github/workflows/contexistdeploy-AutoDeployTrigger-0c7bf7fc-7fed-4f3b-be0c-132dfb27cfc4.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTEXISTDEPLOY_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: antuxtest.azurecr.io
          registryUsername: ${{ secrets.CONTEXISTDEPLOY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTEXISTDEPLOY_REGISTRY_PASSWORD }}
          containerAppName: contexistdeploy
          resourceGroup: OGFs228-0412-gayathri
          imageToBuild: antuxtest.azurecr.io/contexistdeploy:${{ github.sha }}
          dockerfilePath: Dockerfile

     

